"""update cistern defaults

Revision ID: 12c5e3c3b408
Revises: ba22bbe5c3ff
Create Date: 2026-04-06 21:47:22.921548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c5e3c3b408'
down_revision: Union[str, None] = 'ba22bbe5c3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'cistern_capacity_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='3400.0',
               existing_nullable=False)
    op.alter_column('devices', 'cistern_height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='125.0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'cistern_height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'cistern_capacity_liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
