"""Arquitectura_v2.0_completa

Revision ID: ba22bbe5c3ff
Revises: 
Create Date: 2026-04-02 22:09:55.149667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba22bbe5c3ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_types')),
    sa.UniqueConstraint('name', name=op.f('uq_alert_types_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_types')),
    sa.UniqueConstraint('name', name=op.f('uq_sensor_types_name'))
    )
    op.create_table('valve_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('default_state', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valve_types')),
    sa.UniqueConstraint('name', name=op.f('uq_valve_types_name'))
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('name', name=op.f('uq_zones_name'))
    )
    op.create_index(op.f('ix_zones_municipality'), 'zones', ['municipality'], unique=False)
    op.create_index(op.f('ix_zones_zone_code'), 'zones', ['zone_code'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=False),
    sa.Column('cistern_capacity_liters', sa.Float(), nullable=False),
    sa.Column('cistern_height_cm', sa.Float(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_devices_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_zone_id'), 'devices', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_users_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_zone_id'), 'users', ['zone_id'], unique=False)
    op.create_table('device_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=False),
    sa.Column('target_device_id', sa.Integer(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('pipe_diameter_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_device_id <> target_device_id', name=op.f('ck_device_edges_chk_no_self_edge')),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], name=op.f('fk_device_edges_source_device_id_devices')),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], name=op.f('fk_device_edges_target_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_edges')),
    sa.UniqueConstraint('source_device_id', 'target_device_id', name='idx_device_edges_unique')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type_id', sa.Integer(), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=False),
    sa.Column('max_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_threshold <= max_threshold', name=op.f('ck_sensors_chk_sensor_thresholds')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensors_device_id_devices')),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.id'], name=op.f('fk_sensors_sensor_type_id_sensor_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('device_id', 'sensor_type_id', name='idx_sensors_device_type')
    )
    op.create_table('valves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('valve_type_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=10), nullable=False),
    sa.Column('last_commanded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_valves_device_id_devices')),
    sa.ForeignKeyConstraint(['valve_type_id'], ['valve_types.id'], name=op.f('fk_valves_valve_type_id_valve_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valves')),
    sa.UniqueConstraint('device_id', 'valve_type_id', name='idx_valves_device_type')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('alert_type_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_types.id'], name=op.f('fk_alerts_alert_type_id_alert_types')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices')),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alerts_sensor_id_sensors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('idx_alerts_active', 'alerts', ['device_id'], unique=False, postgresql_where=sa.text('is_resolved = false'))
    op.create_index('idx_alerts_payload', 'alerts', ['payload_snapshot'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('valve_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_audit_logs_device_id_devices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.ForeignKeyConstraint(['valve_id'], ['valves.id'], name=op.f('fk_audit_logs_valve_id_valves')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_payload', 'audit_logs', ['payload_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_device_id'), 'audit_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_device_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_payload', table_name='audit_logs', postgresql_using='gin')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_index('idx_alerts_payload', table_name='alerts', postgresql_using='gin')
    op.drop_index('idx_alerts_active', table_name='alerts', postgresql_where=sa.text('is_resolved = false'))
    op.drop_table('alerts')
    op.drop_table('valves')
    op.drop_table('sensors')
    op.drop_table('device_edges')
    op.drop_index(op.f('ix_users_zone_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_active', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_zone_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_zones_zone_code'), table_name='zones')
    op.drop_index(op.f('ix_zones_municipality'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('valve_types')
    op.drop_table('sensor_types')
    op.drop_table('roles')
    op.drop_table('alert_types')
    # ### end Alembic commands ###
