"""Added CheckConstraints for metrics bounds

Revision ID: f199fab1addb
Revises: 12c5e3c3b408
Create Date: 2026-04-06 22:36:44.179302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f199fab1addb'
down_revision: Union[str, None] = '12c5e3c3b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
