apiVersion: 1
datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    access: proxy
    isDefault: false
    jsonData:
      allowedHosts:
        - "http://backend:8000"
      httpHeaderName1: "X-API-Key"
    secureJsonData:
      httpHeaderValue1: "hydrov_grafana_secret_2026"
