[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient@2.8.0
    bblanchon/ArduinoJson@6.21.5
    https://github.com/JChristensen/movingAvg.git
    teckel12/NewPing@1.9.7

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++17
    -Os
    -Wall -Wextra